name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:



jobs:
  build-flutter:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.3'
        
      - name: Install dependencies
        working-directory: ./app
        run: flutter pub get
        
      - name: Prebuild web
        working-directory: ./app
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Create .env file
        working-directory: ./app
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
        
      - name: Build web
        working-directory: ./app
        run: flutter build web --wasm
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './app/build/web'
          
          
  deploy-github-pages:
    runs-on: ubuntu-latest
    needs: build-flutter

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
              
  deploy-supabase:
    runs-on: ubuntu-latest
    needs: build-flutter

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - run: echo 'y' | npx -y supabase@beta db reset --db-url $SUPABASE_DB_URL
      - run: supabase functions deploy --project-ref $PROJECT_ID